export const infancias = {
  title: "Agosto, Mes de las Infancias",
  teaser: {
    headline: "Agosto, Mes de las Infancias",
    description:
      "Actividades, jornadas y encuentros pensados para niñas, niños y adolescentes en toda la provincia. Conocé la agenda, los mapas y los puntos de encuentro.",
    ctaLabel: "Explorar la agenda",
    ctaHref: "/mes-de-las-infancias",
  },
  intro:
    "Durante agosto el Ministerio impulsa una programación especial dedicada a las infancias: juegos, talleres, salud, deporte y cultura en distintas localidades de La Rioja. El contenido de esta página es plantilla de ejemplo y será reemplazado con la información oficial.",
  stats: [
    { value: "48", label: "Actividades programadas" },
    { value: "12", label: "Localidades participantes" },
    { value: "3.200+", label: "Niñas y niños esperados" },
    { value: "20", label: "Días de agenda" },
  ],
  events: [
    {
      id: "evt-1",
      date: "5 de agosto",
      time: "10:00",
      title: "Jornada lúdica en Plaza 25 de Mayo",
      place: "Capital — Plaza 25 de Mayo",
      audience: "Niñas y niños de 3 a 12 años",
    },
    {
      id: "evt-2",
      date: "8 de agosto",
      time: "15:00",
      title: "Taller de lectura y juegos",
      place: "Chilecito — Centro Cultural",
      audience: "Familias con niñas y niños",
    },
    {
      id: "evt-3",
      date: "12 de agosto",
      time: "09:30",
      title: "Feria de salud infantil",
      place: "Aimogasta — Hospital zonal",
      audience: "Comunidad en general",
    },
    {
      id: "evt-4",
      date: "16 de agosto",
      time: "16:00",
      title: "Encuentro deportivo provincial",
      place: "Capital — Predio deportivo",
      audience: "Niñas, niños y adolescentes",
    },
    {
      id: "evt-5",
      date: "22 de agosto",
      time: "11:00",
      title: "Cine al aire libre",
      place: "Villa Unión — Plaza principal",
      audience: "Toda la familia",
    },
    {
      id: "evt-6",
      date: "28 de agosto",
      time: "10:00",
      title: "Cierre provincial del Mes de las Infancias",
      place: "Capital — Predio ferial",
      audience: "Público general",
    },
  ],
  venues: [
    {
      id: "v-1",
      name: "Plaza 25 de Mayo",
      city: "La Rioja Capital",
      address: "Centro cívico",
      note: "Punto principal de actividades lúdicas",
    },
    {
      id: "v-2",
      name: "Centro Cultural Chilecito",
      city: "Chilecito",
      address: "Av. Pelagio B. Luna (ejemplo)",
      note: "Talleres y lectura",
    },
    {
      id: "v-3",
      name: "Hospital zonal",
      city: "Aimogasta",
      address: "Zona hospitalaria (ejemplo)",
      note: "Feria de salud infantil",
    },
    {
      id: "v-4",
      name: "Plaza principal",
      city: "Villa Unión",
      address: "Centro urbano",
      note: "Cine y actividades familiares",
    },
  ],
  mapPoints: [
    {
      id: "p-1",
      name: "La Rioja Capital",
      lat: -29.4135,
      lng: -66.8563,
      description: "Agenda central y cierre provincial",
    },
    {
      id: "p-2",
      name: "Chilecito",
      lat: -29.1624,
      lng: -67.4974,
      description: "Talleres culturales",
    },
    {
      id: "p-3",
      name: "Aimogasta",
      lat: -28.5594,
      lng: -66.8037,
      description: "Feria de salud",
    },
    {
      id: "p-4",
      name: "Villa Unión",
      lat: -29.3178,
      lng: -68.2265,
      description: "Cine al aire libre",
    },
  ],
} as const;
